### ISSUE TITLE
Can't read or create config files

### ISSUE THREAD

**Issue by LeeRobson** [ozguncagri/nwMAME#3]
Hi, I love the design of this frontend and really want to use it, but I can't get it to read or save cfg, ini or nvram files.

The guide said to put everything in the Settings subdirectory and I assume it's supposed to work but I don't know what's wrong.

Can you help, please?

Thanks.

**Comment by ozguncagri** [comment]
I think you are trying to use your own configuration files. Basically working copy of nwMAME will contain files like this;

Directories;
![screen shot 2016-09-28 at 21 31 21](https://cloud.githubusercontent.com/assets/946294/18927075/f6f60a00-85c2-11e6-8122-c5da52c4a4d7.png)

Inside of cfg directory;
![screen shot 2016-09-28 at 21 30 39](https://cloud.githubusercontent.com/assets/946294/18927135/446af7d2-85c3-11e6-9f84-0f45c6cd22f8.png)

Inside of nvram directory;
![screen shot 2016-09-28 at 21 30 55](https://cloud.githubusercontent.com/assets/946294/18927143/555cb77e-85c3-11e6-9867-79333a960189.png)

Currently nwMAME doesn't support for custom INI configs. You can use INI config but you should change mame execution part of source code.

**Comment by LeeRobson** [comment]
Thanks for the fast reply.

I did try to use my own configs at first, but also tried like yours by creating 2 separate folders inside of Settings. Neither worked. Settings aren't saved.

**Comment by ozguncagri** [comment]
Did you select "Mame Output Directory" as you Settings directory on settings window?

**Comment by LeeRobson** [comment]
Yes.

**Comment by ozguncagri** [comment]
Interesting. It should be working. Maybe you can try to run it with zero config. Basically you don't need to do something on Settings directory on zero config. Mame uses it for saving cfg and nvram files. And it could be beacuse of NWJS. Maybe you can try older versions (older than 0.13) of NWJS. Because I haven't tested newer versions of NWJS yet.

**Comment by LeeRobson** [comment]
Still not working, sorry.

Here's a couple of pictures http://imgur.com/a/oiQd5

**Comment by ozguncagri** [comment]
What do you see on Settings > Logs section after trying to run some games?

**Comment by LeeRobson** [comment]
I hoped the log would share some info, but all it ever says is
http://imgur.com/a/Q37R9

The odd thing is, if I change some MAME settings when playing a game (Tab menu) and then quit the game, the settings will still be the same if I play it again. But it's all lost after closing the nwMAME app.

**Comment by ozguncagri** [comment]
Really interesting. Sounds like there is a problem with running in windows but I'm still not sure. nwMAME should save it's own data files in your user libraries. I'm not a Windows user that's why I can't tell exact location but you should see NWJS or nwMAME directory on your user library files. If you can't there is a problem with the writing settings. And also you can try to run nwMAME as an Administrator or you can make some changes on Compatibility Settings of executables.

**Comment by LeeRobson** [comment]
I've discovered what it was! This is going to sound stupid, probably.

It wasn't a permissions issue, it wasn't a NWJS version issue.

To begin with, I followed the guide from here https://github.com/ozguncagri/nwMAME/ and everything worked except the cfg and nvram like I said, but the guide didn't tell me to add all of the files from the top of the page. When I did, it started writing to that directory.

So I'm happy now. Thanks for your patience.

**Comment by ozguncagri** [comment]
I don't get it. Is there any steps that I didn't mentioned on guide? If there is I can update it.

**Comment by LeeRobson** [comment]
At the top of the page, there's an option to clone or download the files there (green button). I thought these were for compiling the app, but it seems I needed something from there to make it work.

**Comment by ozguncagri** [comment]
Actual app package is in the dist folder (app.nw). Rest is just source code. But if you solved it somehow nothing is important :) Enjoy the games :)

**Comment by LeeRobson** [comment]
Yes, it's odd.

Thanks :) I'm having more fun creating custom flyers for games. That's why I like this more than any other MAME frontend, it's got 1 view and it's perfect.

I just need to get glsl working again now, forgot how to do it in standard MAME. I won't bug you about that, though. Then it's all set up.

EDIT: Needed to write the full path for glsl folder and or shader.

**Comment by ozguncagri** [comment]
As I know GLSL and HLSL settings are made with mame.ini file but if you create mame.ini file nwMAME is gonna warn you to delete mame.ini file and won't open game. But if you find executable arguments of your effects you can add it to source code and make it default. I'm gonna add GLSL and HLSL setting on later versions if I can find time to develop next version.

**Comment by LeeRobson** [comment]
I edited the post above. Works now.

Adding settings would be excellent. Would you also be able to add joystick support for the menu?

And I know this is exclusively a MAME frontend, but would it be possible to launch other games through it? I'd love to combine my MAME favourtes with other games from other emulators like Metal Slug 6 on Demul. It would just need to launch a bat file.

**Comment by ozguncagri** [comment]
I was considering joystick support for front-end already. And I will definitely consider support for other emulators and stand alone games. Thank you for your feedback :)

**Comment by LeeRobson** [comment]
Brilliant! You rock.
